-- shared/items.lua
--
-- isFood        = true/false   → activer/désactiver l'effet nourriture/boisson
-- foodType      = 'food'/'drink' → 'food' restaure la faim, 'drink' restaure la soif
-- restoreAmount = nombre       → combien ça restaure (sur 100)
--
Items = {
    ['water_bottle'] = {
        name        = 'water_bottle',
        label       = 'Bouteille d\'eau',
        description = 'Une bouteille d\'eau fraîche. Restaure la soif.',
        weight      = 0.5,
        stackable   = true,
        maxStack    = 10,
        icon        = '💧',
        usable      = true,
        isFood        = true,       -- c'est un item consommable
        foodType      = 'drink',    -- restaure la soif
        restoreAmount = 25.0,       -- +25 soif (sur 100)
    },
    ['bread'] = {
        name        = 'bread',
        label       = 'Pain',
        description = 'Une miche de pain. Restaure la faim.',
        weight      = 0.3,
        stackable   = true,
        maxStack    = 5,
        icon        = '🍞',
        usable      = true,
        isFood        = true,       -- c'est un item consommable
        foodType      = 'food',     -- restaure la faim
        restoreAmount = 25.0,       -- +25 faim (sur 100)
    },
    ['money'] = {
        name        = 'money',
        label       = 'Argent',
        description = 'Ce qui sert a vivre',
        weight      = 0.01,
        stackable   = true,
        maxStack    = 100000000,
        icon        = '💸',
        usable      = false,
    },
    ['lockpick'] = {
        name        = 'lockpick',
        label       = 'Crochetage',
        description = 'Je pense que avec ca tu vas aller loin',
        weight      = 1,
        stackable   = true,
        maxStack    = 10,
        icon        = '🪝',
        usable      = true,
    },
    ['vehicle_key'] = {
        name        = 'vehicle_key',
        label       = 'Cle de vehicule',
        description = 'Une cle de vehicule',
        weight      = 0.1,
        stackable   = false,
        maxStack    = 1,
        icon        = '🔑',
        usable      = false,
        hasMetadata = true,
    },
    -- ═══ Items Weed System ═══
    ['weed_leaf'] = {
        name        = 'weed_leaf',
        label       = 'Feuille de Weed',
        description = 'Une feuille de weed prete a etre plantee.',
        weight      = 0.1,
        stackable   = true,
        maxStack    = 50,
        icon        = '🌿',
        usable      = true,
    },
    ['white_widow'] = {
        name        = 'white_widow',
        label       = 'White Widow',
        description = 'De la White Widow fraichement recoltee.',
        weight      = 0.2,
        stackable   = true,
        maxStack    = 50,
        icon        = '🍁',
        usable      = true,
        consumeOnUse = false,
    },
    ['pochon_white_widow'] = {
        name        = 'pochon_white_widow',
        label       = 'Pochon de White Widow',
        description = 'Un pochon de White Widow pret a la vente.',
        weight      = 0.3,
        stackable   = true,
        maxStack    = 30,
        icon        = '💚',
        usable      = false,
    },
    ['pochon_vide'] = {
        name        = 'pochon_vide',
        label       = 'Pochon Vide',
        description = 'Un pochon vide pour conditionner la marchandise.',
        weight      = 0.05,
        stackable   = true,
        maxStack    = 50,
        icon        = '🛍️',
        usable      = false,
    },
    ['arrosoir'] = {
        name        = 'arrosoir',
        label       = 'Arrosoir',
        description = 'Un arrosoir pour hydrater les plantes.',
        weight      = 1.0,
        stackable   = false,
        maxStack    = 1,
        icon        = '🚿',
        usable      = true,
        consumeOnUse = false,
    },
    ['ciseau'] = {
        name        = 'ciseau',
        label       = 'Ciseau',
        description = 'Un ciseau pour recolter les plantes.',
        weight      = 0.5,
        stackable   = false,
        maxStack    = 1,
        icon        = '✂️',
        usable      = true,
        consumeOnUse = false,
    },
    ['pot_terre'] = {
        name        = 'pot_terre',
        label       = 'Pot de terre',
        description = 'Un pot en terre cuite pour la culture.',
        weight      = 2.0,
        stackable   = true,
        maxStack    = 5,
        icon        = '🏺',
        usable      = true,
    },
    ['terreau'] = {
        name        = 'terreau',
        label       = 'Terreau',
        description = 'Du terreau fertile pour faire pousser des plantes.',
        weight      = 1.0,
        stackable   = true,
        maxStack    = 10,
        icon        = '🪴',
        usable      = true,
    },
    -- ═══ Items Drogues (Go Fast) ═══
    ['cocaine_brick'] = {
        name        = 'cocaine_brick',
        label       = 'Brique de Cocaïne',
        description = 'Un bloc compact de poudre blanche. Environ 1kg.',
        weight      = 1.0,
        stackable   = true,
        maxStack    = 20,
        icon        = '🧊',
        usable      = false,
    },
    ['weed_brick'] = {
        name        = 'weed_brick',
        label       = 'Brique de Weed',
        description = 'Un bloc compresse d\'herbe seche. Environ 1kg.',
        weight      = 1.0,
        stackable   = true,
        maxStack    = 20,
        icon        = '🟩',
        usable      = false,
    },
    ['ecstasy_bag'] = {
        name        = 'ecstasy_bag',
        label       = 'Sachet d\'Ecstasy',
        description = 'Un sachet rempli de cachets colores. Environ 1kg.',
        weight      = 1.0,
        stackable   = true,
        maxStack    = 20,
        icon        = '💊',
        usable      = false,
    },
}
