fx_version 'cerulean'
game 'gta5'

author      'Custom'
description 'Inventory & Weapons System - Custom NUI'
version     '2.0.0'

shared_scripts {
    'shared/items.lua',
    'shared/config.lua',
    'shared/weapons.lua',
}

client_scripts {
    'client/main.lua',
    'client/nui.lua',
    'client/weapons.lua',
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'server/main.lua',
    'server/database.lua',
    'server/weapons.lua',
    'server/vehicle.lua',
}

server_exports {
    'giveWeapon',
    'getPlayerWeapons',
    'removeWeapon',
    'getWeaponList',
    'getWeaponCategories',
    'HasItem',
    'RemoveItem',
    'addItemWithMetadata',
    'removeItemByMetadata',
    'hasItemWithMetadata',
    'getItemsMetadata',
    'addItemToVehicle',
}

ui_page 'html/index.html'

files {
    'html/index.html',
    'html/css/style.css',
    'html/js/app.js',
    'html/img/weapons/weapon_advancedrifle.png',
    'html/img/weapons/weapon_appistol.png',
    'html/img/weapons/weapon_assaultrifle.png',
    'html/img/weapons/weapon_assaultrifle_mk2.png',
    'html/img/weapons/weapon_assaultshotgun.png',
    'html/img/weapons/weapon_assaultsmg.png',
    'html/img/weapons/weapon_autoshotgun.png',
    'html/img/weapons/weapon_bat.png',
    'html/img/weapons/weapon_battleaxe.png',
    'html/img/weapons/weapon_bottle.png',
    'html/img/weapons/weapon_bullpuprifle.png',
    'html/img/weapons/weapon_bullpuprifle_mk2.png',
    'html/img/weapons/weapon_bullpupshotgun.png',
    'html/img/weapons/weapon_bzgas.png',
    'html/img/weapons/weapon_carbinerifle.png',
    'html/img/weapons/weapon_carbinerifle_mk2.png',
    'html/img/weapons/weapon_ceramicpistol.png',
    'html/img/weapons/weapon_combatmg.png',
    'html/img/weapons/weapon_combatmg_mk2.png',
    'html/img/weapons/weapon_combatpdw.png',
    'html/img/weapons/weapon_combatpistol.png',
    'html/img/weapons/weapon_combatshotgun.png',
    'html/img/weapons/weapon_compactlauncher.png',
    'html/img/weapons/weapon_compactrifle.png',
    'html/img/weapons/weapon_crowbar.png',
    'html/img/weapons/weapon_dagger.png',
    'html/img/weapons/weapon_dbshotgun.png',
    'html/img/weapons/weapon_doubleaction.png',
    'html/img/weapons/weapon_firework.png',
    'html/img/weapons/weapon_flare.png',
    'html/img/weapons/weapon_flaregun.png',
    'html/img/weapons/weapon_gadgetpistol.png',
    'html/img/weapons/weapon_golfclub.png',
    'html/img/weapons/weapon_grenade.png',
    'html/img/weapons/weapon_grenadelauncher.png',
    'html/img/weapons/weapon_gusenberg.png',
    'html/img/weapons/weapon_hammer.png',
    'html/img/weapons/weapon_hatchet.png',
    'html/img/weapons/weapon_heavypistol.png',
    'html/img/weapons/weapon_heavyrifle.png',
    'html/img/weapons/weapon_heavyshotgun.png',
    'html/img/weapons/weapon_heavysniper.png',
    'html/img/weapons/weapon_heavysniper_mk2.png',
    'html/img/weapons/weapon_hominglauncher.png',
    'html/img/weapons/weapon_knife.png',
    'html/img/weapons/weapon_machete.png',
    'html/img/weapons/weapon_machinepistol.png',
    'html/img/weapons/weapon_marksmanpistol.png',
    'html/img/weapons/weapon_marksmanrifle.png',
    'html/img/weapons/weapon_marksmanrifle_mk2.png',
    'html/img/weapons/weapon_mg.png',
    'html/img/weapons/weapon_microsmg.png',
    'html/img/weapons/weapon_militaryrifle.png',
    'html/img/weapons/weapon_minigun.png',
    'html/img/weapons/weapon_minismg.png',
    'html/img/weapons/weapon_molotov.png',
    'html/img/weapons/weapon_musket.png',
    'html/img/weapons/weapon_navyrevolver.png',
    'html/img/weapons/weapon_nightstick.png',
    'html/img/weapons/weapon_pipebomb.png',
    'html/img/weapons/weapon_pistol.png',
    'html/img/weapons/weapon_pistol50.png',
    'html/img/weapons/weapon_pistol_mk2.png',
    'html/img/weapons/weapon_poolcue.png',
    'html/img/weapons/weapon_precisionrifle.png',
    'html/img/weapons/weapon_proxmine.png',
    'html/img/weapons/weapon_pumpshotgun.png',
    'html/img/weapons/weapon_pumpshotgun_mk2.png',
    'html/img/weapons/weapon_railgun.png',
    'html/img/weapons/weapon_revolver.png',
    'html/img/weapons/weapon_revolver_mk2.png',
    'html/img/weapons/weapon_rpg.png',
    'html/img/weapons/weapon_sawnoffshotgun.png',
    'html/img/weapons/weapon_smg.png',
    'html/img/weapons/weapon_smg_mk2.png',
    'html/img/weapons/weapon_smokegrenade.png',
    'html/img/weapons/weapon_sniperrifle.png',
    'html/img/weapons/weapon_snspistol.png',
    'html/img/weapons/weapon_snspistol_mk2.png',
    'html/img/weapons/weapon_specialcarbine.png',
    'html/img/weapons/weapon_specialcarbine_mk2.png',
    'html/img/weapons/weapon_stickybomb.png',
    'html/img/weapons/weapon_stone_hatchet.png',
    'html/img/weapons/weapon_switchblade.png',
    'html/img/weapons/weapon_tacticalrifle.png',
    'html/img/weapons/weapon_vintagepistol.png',
    'html/img/weapons/weapon_wrench.png',
}
